spring:
  application:
    name: proxy-service
#server:
#  port: 8303

zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: https://db-service.stock-quote-tp.appspot.com/
    stock-service:
      path: /stock-service/**
      url: http://stock-service.stock-quote-tp.appspot.com
